# Generated by Django 4.1.4 on 2023-01-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tag_delete_label_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tasks', to='base.tag'),
        ),
    ]
