# Generated by Django 4.1.4 on 2023-01-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Important'), ('2', 'Very important')], default='0', max_length=1),
        ),
    ]
